# Generated by Django 4.2.4 on 2023-08-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_users',
        ),
    ]
