# Generated by Django 4.2.4 on 2023-09-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_sellerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='name',
            new_name='ownername',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
