# Generated by Django 4.2.4 on 2023-09-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_application_category_product_certification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='first_name',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='last_name',
            new_name='store_name',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certification_authority',
        ),
    ]
