# Generated by Django 4.2.4 on 2023-09-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_first_name_certification_owner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='default_product_price',
        ),
    ]
