# Generated by Django 4.2.4 on 2023-09-12 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0015_alter_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatus',
            name='application',
        ),
        migrations.AddField(
            model_name='certification',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=user.models.Seller, on_delete=django.db.models.deletion.CASCADE, to='user.seller'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
    ]
