# Generated by Django 4.2.4 on 2023-09-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_certification_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
