# Generated by Django 4.2.4 on 2023-09-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_certification_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
