# Generated by Django 4.2.4 on 2023-09-16 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_seller_email_seller_name_seller_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='profile_pic',
        ),
    ]
