# Generated by Django 4.2.4 on 2023-09-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_seller_email_remove_seller_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
