# Generated by Django 4.2.4 on 2023-09-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_productsummary_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsummary',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
