# Generated by Django 4.2.4 on 2023-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_productsummary_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsummary',
            name='humidity_requirements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsummary',
            name='light_requirements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsummary',
            name='maintenance_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsummary',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsummary',
            name='toxicity_information',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productsummary',
            name='water_requirements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
