# Generated by Django 4.2.4 on 2023-09-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_productsummary_toxicity_information_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
