# Generated by Django 4.2.4 on 2023-09-23 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsummary',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_summary', to='user.product'),
        ),
    ]
