# Generated by Django 4.2.4 on 2023-09-28 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_productsummary_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsummary',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_summaries', to='user.category'),
        ),
    ]
