# Generated by Django 4.2.4 on 2023-09-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_productsummary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='opening_days',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=100),
        ),
        migrations.AddField(
            model_name='certification',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='opening_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
