# Generated by Django 4.2.4 on 2023-10-02 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.seller'),
        ),
    ]
