# Generated by Django 4.2.4 on 2023-10-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_order_customer_is_approved_order_seller_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsummary',
            name='stock_is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
