# Generated by Django 4.2.4 on 2023-10-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_productsummary_stock_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
    ]
