# Generated by Django 4.2.4 on 2023-10-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_alter_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_status',
            field=models.CharField(choices=[('reviewed', 'reviewed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
