# Generated by Django 4.2.4 on 2023-10-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_review_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_is_approved',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller_is_approved',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer_is_approved',
            field=models.CharField(choices=[('collected', 'collected'), ('notcollected', 'notcollected')], default='notcollected', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
